'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SiphonServiceAdministration
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SiphonServiceAdministration.ISiphonServiceAdministration")>  _
    Public Interface ISiphonServiceAdministration
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISiphonServiceAdministration/Process", ReplyAction:="http://tempuri.org/ISiphonServiceAdministration/ProcessResponse")>  _
        Sub Process(ByVal name As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ISiphonServiceAdministrationChannel
        Inherits SiphonServiceAdministration.ISiphonServiceAdministration, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SiphonServiceAdministrationClient
        Inherits System.ServiceModel.ClientBase(Of SiphonServiceAdministration.ISiphonServiceAdministration)
        Implements SiphonServiceAdministration.ISiphonServiceAdministration
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Process(ByVal name As String) Implements SiphonServiceAdministration.ISiphonServiceAdministration.Process
            MyBase.Channel.Process(name)
        End Sub
    End Class
End Namespace
